### ISSUE TITLE
This is happening please solve

### ISSUE THREAD

**Issue by phnxXD** [HeimanPictures/Pdisk-Upload-Bot#1]
![IMG_20211006_194358](https://user-images.githubusercontent.com/76841477/136220732-e0f9b3cb-0723-4bf5-a804-76f415f9959f.jpg)

**Comment by HeimanPictures** [comment]
So Send Video with Title this error will not occur..

Don't Worry About It

**Comment by phnxXD** [comment]
No bro bot doesn't respond on /start command
